name: Data Contract CLI
description: 'Run Data Contract Tests'
inputs:
  location:  
    description: The location (url or path) of the data contract yaml. 
    required: true
    default: 'datacontract.yaml'
runs:
  using: 'docker'
  image: 'docker://datacontract/cli:snapshot-latest'
  args:
    - test
    - ${{ inputs.location }}
